spring:
  application:
    name: config-server-profile

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vishymails/environment-variable-repo.git

server:
  port: ${port:8888}